name: Build on macOS

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "licenses/**"

jobs:
  build-macos:
    uses: ./.github/workflows/common-flow-host.yml
    with:
      env: macos-11
      get-redis: true
    secrets: inherit
