name: Build on Linux

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "licenses/**"

jobs:
  build-linux-jammy:
    uses: ./.github/workflows/common-flow-host.yml
    with:
      env: ubuntu-22.04
      get-redis: true
      deps-install-mode: sudo
    secrets: inherit
