name: default (common) flow for container runs

on:
  workflow_call:
    inputs:
      env:
        default: "ubuntu-latest"
        type: string
      container:
        required: true
        type: string
      container_options:
        type: string
        default: --cpus 2
      san:
        type: string
      get-redis:
        type: boolean
      redis-ref: # Only used if get-redis is true. Allows to specify a specific ref to checkout (barnch, tag, commit...)
        type: string
      deps-install-mode:
        type: string
        default: ""
        description: "How to install dependencies. User mode is the default, pass 'sudo' to install as root."
      boost-version:
        type: string
        default: "1.82.0"

jobs:
  common-flow:
    runs-on: ${{ inputs.env }}
    container:
      image: ${{ inputs.container }}
      options: ${{ inputs.container_options }}
# From this point on, this file should be identical to the other common flow.
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: ${{ inputs.deps-install-mode }} ./.install/install_script.sh
      - name: Setup Repo
        run: |
          git init
          git config --global --add safe.directory '*'
          git submodule update --init --recursive
      - name: Restoring cached Boost
        id: boost-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            /$HOME/**/boost
            /$HOME/lib/**/libboost*
          key: boost-${{ inputs.boost-version }}-${{ inputs.container || inputs.env }}
      - name: Get Boost
        if: steps.boost-cache.outputs.cache-hit != 'true'
        run: ${{ inputs.deps-install-mode }} ./.install/install_boost.sh ${{ inputs.boost-version }}
      - name: Saving Boost cache
        uses: actions/cache/save@v3
        if: steps.boost-cache.outputs.cache-hit != 'true'
        with:
          path: |
            /$HOME/**/boost
            /$HOME/lib/**/libboost*
          key: ${{ steps.boost-cache.outputs.cache-primary-key }}
      - name: Get Redis
        if: ${{ inputs.get-redis }}
        uses: actions/checkout@v3
        with:
          repository: redis/redis
          ref: ${{ inputs.redis-ref || '7.2' }}
          path: redis
      - name: Build Redis
        if: ${{ inputs.get-redis }}
        working-directory: redis
        run: ${{ inputs.deps-install-mode }} make install
        #
      # - name: Build
      #   run: |
      #     make SAN=${{ inputs.san }}
      #     make COORD=1 SAN=${{ inputs.san }}
      # - name: Unit tests
      #   run: |
      #     make unit-tests LOG=1 CLEAR_LOGS=0 SAN=${{ inputs.san }}
      # - name: Flow tests
      #   run: |
      #     make pytest QUICK=1 LOG=1 CLEAR_LOGS=0 SAN=${{ inputs.san }}
      # - name: Unit tests (coordinator)
      #   run: |
      #     make COORD=1 unit-tests LOG=1 CLEAR_LOGS=0 SAN=${{ inputs.san }}
      # - name: Flow tests (coordinator)
      #   run: |
      #     make COORD=1 pytest QUICK=1 LOG=1 CLEAR_LOGS=0 SAN=${{ inputs.san }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Test Logs
          path: |
            tests/logs
            tests/pytests/logs/*.log
          if-no-files-found: ignore
      - name: Upload Sanitizer Artifacts
        if: ${{ inputs.san }}
        uses: actions/upload-artifact@v3
        with:
          name: Sanitizer Logs
          path: tests/pytests/logs/*.log.*
          if-no-files-found: ignore
