name: CLang Sanitizer

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "licenses/**"

jobs:
  clang-sanitizer:
    uses: ./.github/workflows/common-flow-host.yml
    with:
      env: ubuntu-22.04
      deps-install-mode: sudo
      san: addr
    secrets: inherit
